# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadGitHubRelease@0
      inputs:
        connection: github
        userRepository: cloudfoundry-incubator/bosh-backup-and-restore
        defaultVersionType: latest
    - task: DownloadGitHubRelease@0
      inputs:
        connection: github
        userRepository: pivotal-cf/om
        defaultVersionType: latest
    - bash: |
        cp $(System.ArtifactsDirectory)/* $(Build.SourcesDirectory)
        echo "HERE'S THE SOURCES DIRECTORY"
        ls $(Build.SourcesDirectory)
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/assets/Dockerfile'
        tags: |
          $(tag)
